### PR TITLE
Argument parsing bugfix, plus writeout suppression options.

### PR DESCRIPTION
**Pull request by dotsdl**

### CODE REVIEW

**Comment by cstein** [comment]
@dotsdl I just looked at the proposed changes in this pull request along with your initial discussion about suppresion of output in issue #10 and I have a few comments and questions I'd like to discuss with the maintainers (I suppose @charnley is the one right now).

The suppression of output, I feel, is a great addition that could be interesting to do in circomstances like yours - especially if you are truly limited by the output of propka. But since it would be a major undertaking (and you are the first to request this suppresion), have you tried using [redirects](http://www.tldp.org/LDP/abs/html/io-redirection.html), i.e.

    propka > std.out

which will remove the output you do not need. Alternatively, if you feel like discarding it entirely you can always redirect to `/dev/null` instead. This will not impact your own scripts at all.

Returning to the the proposed set of changes you have given in this pull request I think that the output suppresion should, for now, be discarded or at least put in issue #10. Your bug-fix regarding the input parameter processing is of course a welcome addition.

Perhaps @charnley can comment on what he thinks and how to proceed.

**Comment by dotsdl** [comment]
I think there may be a bit of confusion on the motivation for these changes. I am not running propka from the shell, but instead feeding ``propka.run.single()`` a PDB structure via a named pipe. I then access the results from the ``Molecular_container`` object to get what I need. Any files written to disk are not used, and this is all done within python, not a shell.

The output displayed to stdout is a separate issue, and one that I haven't addressed at all in these commits. I realize that adding options for suppressing printed output isn't a particularly exciting feature, but it makes it much easier to envision propka being used on whole trajectories inside of larger codebases if this were the case.

**Comment by cstein** [comment]
Ahh, I understand now and can see why your particular setup would require this suppression.

The propka code is littered with `print(str)` statements, so you are indeed correct that it is not the most exciting thing to implement. Let's keep the discussion on the output suppression in #10.

**Comment by orbeckst** [comment]
@dotsdl I think you can close this PR. The `--quiet` keyword does what was needed.

**Comment by dotsdl** [comment]
@orbeckst yeah probably fine to close this for now. Will check out the changes from #12.

**Pull request closed without merging**
